account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from . import views
from .forms import(UserLoginForm, PwdResetForm, PwdResetConfirmForm)

app_name = 'account'

#All the account urls

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html', form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/password_reset/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/', 
                                                                                                form_class=PwdResetConfirmForm), name="password_reset_confirm"),
    
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_done'),

    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_complete'),
                                                                                                
    #user dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name = "account/dashboard/delete_confirm.html"), name='delete_confirmation'),
]

basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

#all urls in the basket application
urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

#These are the core urls that lead to the separate apps

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

#All urls for the store app
urlpatterns = [
    path('', views.product_all, name='store_home'),
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

#This class allows to the superuser to activate and deactivate items in the store
class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)

#This class allows to add a category to the store
class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name

#This class creates a table with all product details in the database
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

store/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product

# Create your views here.

#This view return all products
def product_all(request):
    products = Product.objects.all()
    return render(request, 'store/index.html', {'products':products})

#This view returns all product details when a specific item is clicked in the website
def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/single.html', {'product':product})

#This is the category list/dropdown menu witch is powered by this view
def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.products.filter(category=category)
    return render(request, 'store/category.html', {'category':category, 'products':products})

templates/store/category.html
{% extends "../base.html" %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}

    <!--
      Displaying all products of a specific category
    -->

    <div class="album py-5 bg-light">
      <div class="container">
        <div class="pb-3 h5">{{category.name|title}}</div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
          {% for product in products %}
          <div class="col">
            <div class="card shadow-sm">
              <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
              <div class="card-body">
                <p class="card-text">
                  <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <small class="text-muted">9min read</small>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
{% endblock %}

templates/store/index.html
{% extends "base.html" %}
{% block title %}PhoneAccessories{% endblock %}

{% block content %}

    <!--
      When you enter the website and you are not logged this is the big setion that tells you to register
    -->

    {% if user.is_authenticated %}
    <div>
      
    </div>
    {% else %}
    <section class="py-5 text-center container">
      <div class="row py-lg-1">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="h1 fw-bold">Всички аксесоари за твоя телефон на едно място!</h1>
          <p class="lead text-muted"></p>
          <p>
            <a href="{% url "account:register" %}" class="btn btn-primary my-2">Направи си акаунт</a>
          </p>
        </div>
      </div>
    </section>
    {% endif %}
    
    <!--
      Displays all items avairable in the store
    -->

    <div class="album py-5 bg-light">
      <div class="container">
        <div class="pb-3 h5">Всички аксесоари</div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
          {% for product in products %}
          <div class="col">
            <div class="card shadow-sm">
              <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
              <div class="card-body">
                <p class="card-text">
                  <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </p>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
{% endblock %}

templates/store/single.html
{% extends "../base.html" %}
{% block title %}
{% if product %}{{ product.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div class="container" style="max-width: 1000px">
      <div class="row g-3">
          <div class="col-12 d-flex justify-content-between">
          </div>
          <!--
            Product quantity selection dropdown menus
          -->
          <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
              <div class="d-grid gap-2">
              <div class="d-flex d-flex-inline justify-content-between">
              <div><span class="h3">{{ product.price }} лв.</span><p class="text-muted">включено ддс</p></div>
                     <div class="">
                                  <label for="select">Количество</label>
                                  <select id="select" class="h6" style="width:50px;height:40px;">
                                      <option value="1">1</option>
                                      <option value="2">2</option>
                                      <option value="3">3</option>
                                      <option value="4">4</option>
                                  </select>
                      </div>
              </div>
              <div class="description">
                {{product.description}}
              </div>
              <hr>
              <button type="button" id="add-button" value="{{product.id}}" class="btn btn-success fw500">Добави в количка</button>
              </div>
          </div>
          <div class="col-md-7 col-lg-7 p-0">
              <div class="card mb-3 border-0">
              <div class="row g-0">
                  <div class="col-md-12">
                      <div class="card-body p-1">
                          <h1 class="mb-0 h2 pe-4 pb-4">{{ product.title }}</h1>
                          <div class="bg-light"><img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}"> </div>
                      </div>
                  </div>
              </div>
              </div>
          </div>
      </div>
    </div>
  </main>
  
<!--
    Ajax script to update item quantity in cart
-->

  <script>
      $(document).on('click', '#add-button', function (e) {
          e.preventDefault();
          $.ajax({
              type: 'POST',
              url: '{% url "basket:basket_add" %}',
              data: {
                  productid: $('#add-button').val(),
                  productqty: $('#select option:selected').text(),
                  csrfmiddlewaretoken: "{{csrf_token}}",
                  action: 'post'
              },
              success: function (json) {
                 document.getElementById("basket-qty").innerHTML = json.qty
              },
              error: function (xhr, errmsg, err) {}
          });
      })
  </script>

{% endblock %}